version: '3.9'

services:
  db:
    container_name: iluvcoffee-db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: iluvcoffee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
  backend:
    container_name: iluvcoffee-backend
    image: iluvcoffee/backend:latest
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - default

networks:
  default:
